---
- hosts: ungrouped
  vars:
    system_owner: nikhilpatel@ansible.com
  tasks:
    - template:
        src: jinja2/motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
    
